id: julep-strainers
name: Julep Strainers
products:
  - name: Julep Strainer
    stores:
      - name: Amazon
        link: https://www.amazon.com/Julep-Strainer-Stainless-Cocktail-Supply/dp/B07CN7WMVP
